#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

boot()
{
    echo "will be started via hotplug"
}

start_service()
{
    procd_open_instance "phantap-learn"
    procd_set_param command /usr/sbin/phantap-learn -i br-phantap
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
